### ISSUE TITLE
Add the dependencies of tailwind and post css

### ISSUE THREAD

**Issue by rehan-ssh** [helpshift/helpshift-webchat-examples#6]
Please add these dependencies in react code as well @dv-Gogna 

https://github.com/helpshift/helpshift-webchat-examples/blob/f2ade1c0f184f0912ba8baed84c95d31e8996375/react/package.json#L24

    "postcss": "^8",
    "tailwindcss": "^3.4.1"
    "autoprefixer": "^10.4.19"

**Comment by dv-Gogna** [comment]
Done the changes.
